// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using RestauranteApi.Contexto;
using System;

namespace RestauranteApi.Migrations
{
    [DbContext(typeof(RestauranteContexto))]
    partial class RestauranteContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("RestauranteApi.Models.Prato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SQPRATO");

                    b.Property<string>("Decricao")
                        .IsRequired()
                        .HasColumnName("NMPRATO")
                        .HasMaxLength(255);

                    b.Property<long>("RestauranteId")
                        .HasColumnName("SQRESTAURANTE");

                    b.HasKey("Id")
                        .HasName("PKPRATO");

                    b.HasIndex("RestauranteId");

                    b.ToTable("PRATO");
                });

            modelBuilder.Entity("RestauranteApi.Models.Restaurante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SQRESTAURANTE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("NMRESTAURANTE")
                        .HasMaxLength(255);

                    b.HasKey("Id")
                        .HasName("PKRESTAURANTE");

                    b.ToTable("Restaurante");
                });

            modelBuilder.Entity("RestauranteApi.Models.Prato", b =>
                {
                    b.HasOne("RestauranteApi.Models.Restaurante", "Restaurante")
                        .WithMany("Pratos")
                        .HasForeignKey("RestauranteId")
                        .HasConstraintName("FKRESTAURANTEPRATO")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
